site_name: Tiny Bank Documentation
site_author: Thiago Nascimento Figueiredo
site_description: >-
  Documentation site for Tiny Bank sample application

# Configuration
theme:
  name: material

# Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  features:
    palette:
      - scheme: lmn
    font:
      text: Ubuntu
      code: Ubuntu Mono

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - index.md
  - test-documentation.md
  - Architectural Decision Records:
      - adrs/ADR00-project-decisions-documentation.md
      - adrs/ADR01-use-docker-to-present-project-documentation.md
      - adrs/ADR02-use-MkDocs-to-present-markdown-content.md
      - adrs/ADR03-use-BDD-for-test-approach.md
      - adrs/ADR04-use-C4-Model-for-diagrams.md
      - adrs/ADR05-use-map-structure-to-store-data.md
      - adrs/ADR06-no-login-implementation.md
      - adrs/ADR06-no-login-implementation.md
      - adrs/ADR07-provide-interface-to-interact-with-api.md
      - adrs/ADR08-application-layers.md
      - adrs/ADR09-exception-handling.md
      - adrs/ADR10-BDD-tests-operations-approach.md