@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_WITH_LEGEND()

title Tiny Bank 2.0

Person(customer, "Banking Customer", "A customer of the bank, with personal bank accounts.")
System(banking_system, "Internet Banking System", "Allows customers to interact with their bank accounts and verify transactions operations.")

System(account_operations, "Banking On-line Data", "Saves all data for the current state of entities project-related data.")
System(account_events, "Events Repository", "Stores the events related to some users actions in the Tiny Bank 2.0 scope.")

Rel(customer, banking_system, "Uses")
Rel_Neighbor(banking_system, account_operations, "Saves data")
Rel(banking_system, account_events, "Store Events")
@enduml